version: '3'
services:
  # CONFIGURAÇÕES MYSQL
  db_mysql:
    container_name: db_mysql
    image: mysql:8.0.32-oracle
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    tty: true
    ports:
      - "3336:3306"
    volumes:
      - ./db/mysql/dbdata:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=database_fiap
      - MYSQL_ROOT_PASSWORD=root
  app:
    build: app
    container_name: app
    working_dir: /app
    restart: always
    tty: true
    volumes:       
      - ./app:/app
    # command: ["./mvnw", spring-boot:run"]
    